export const aud = 
[
 "../assets/aud/2CELLOS - Thunderstruck.mp3",
 "../assets/aud/2Pac - Hail Mary.mp3",
 "../assets/aud/2Pac - Resist The Temptation.mp3",
 "../assets/aud/2Pac, Big Syke - All Eyez On Me (ft. Big Syke).mp3",
 "../assets/aud/03 BOILED PEANUTS.mp3",
 "../assets/aud/03 Playing God.mp3",
 "../assets/aud/3TEETH - PUMPED UP KICKS.mp3",
 "../assets/aud/3TEETH, Ho99o9 - Lights Out.mp3",
 "../assets/aud/04 Brick By Boring Brick.mp3",
 "../assets/aud/04 DENIAL IS A RIVER.mp3",
 "../assets/aud/05 CATFISH.mp3",
 "../assets/aud/05 Turn It Off.mp3",
 "../assets/aud/5 Seconds of Summer - Youngblood.mp3",
 "../assets/aud/06 SKIPP.mp3",
 "../assets/aud/06 The Only Exception.mp3",
 "../assets/aud/07 Feeling Sorry.mp3",
 "../assets/aud/07 HIDE N SEEK.mp3",
 "../assets/aud/08 BLOOM.mp3",
 "../assets/aud/08 Looking Up.mp3",
 "../assets/aud/09 WAIT.mp3",
 "../assets/aud/09 Where The Lines Overlap.mp3",
 "../assets/aud/10 DEATH ROLL.mp3",
 "../assets/aud/10 Misguided Ghosts.mp3",
 "../assets/aud/11 All I Wanted.mp3",
 "../assets/aud/11 PROFIT.mp3",
 "../assets/aud/12 BOOM BAP.mp3",
 "../assets/aud/12 Decode [Twilight Soundtrack Version].mp3",
 "../assets/aud/13 NISSAN ALTIMA.mp3",
 "../assets/aud/14 GTFO.mp3",
 "../assets/aud/15 HUH!.mp3",
 "../assets/aud/16 SLIDE.mp3",
 "../assets/aud/17 FIREFLIES.mp3",
 "../assets/aud/18 BEVERLY HILLS.mp3",
 "../assets/aud/19 ALLIGATOR BITES NEVER HEAL.mp3",
 "../assets/aud/45 Grave - Riboflavin.mp3",
 "../assets/aud/50 Cent - P.I.M.P..mp3",
 "../assets/aud/1000mods - Abell 1835.mp3",
 "../assets/aud/1000mods - Road to Burn.mp3",
 "../assets/aud/1000mods - Track Me.mp3",
 "../assets/aud/1000mods - Vidage.mp3",
 "../assets/aud/1782 - Oh Mary.mp3",
 "../assets/aud/1782 - She Was a Witch.mp3",
 "../assets/aud/3005.mp3",
 "../assets/aud/A Perfect Circle - The Outsider.mp3",
 "../assets/aud/A Static Lullaby - Toxic (Britney Spears Cover).mp3",
 "../assets/aud/Aaliyah - Back & Forth.mp3",
 "../assets/aud/ABBA - Dancing Queen.mp3",
 "../assets/aud/Able Heart - Masterpiece.mp3",
 "../assets/aud/Acid Bath - Bleed Me an Ocean.mp3",
 "../assets/aud/Acid Bath - Finger Painting Of The Insane.mp3",
 "../assets/aud/Acid Bath - Tranquilized.mp3",
 "../assets/aud/aespa, TOKiMONSTA - Die Trying.mp3",
 "../assets/aud/AG - Terrible Thing.mp3",
 "../assets/aud/Agnes Obel - It's Happening Again.mp3",
 "../assets/aud/Agnes Obel - Run Cried the Crawling.mp3",
 "../assets/aud/Agnes Obel - The Curse.mp3",
 "../assets/aud/Air - Sexy Boy.mp3",
 "../assets/aud/Airhead.mp3",
 "../assets/aud/Al Green - Love and Happiness.mp3",
 "../assets/aud/Alabama Shakes - Don't Wanna Fight.mp3",
 "../assets/aud/Alabama Shakes - Dunes.mp3",
 "../assets/aud/Alabama Shakes - Future People.mp3",
 "../assets/aud/Alannah Myles   Black Velvet HD.mp3",
 "../assets/aud/Alex Cameron - Far From Born Again.mp3",
 "../assets/aud/Algiers - Death March.mp3",
 "../assets/aud/Alice Phoebe Lou - Witches.mp3",
 "../assets/aud/All Them Witches - 1X1.mp3",
 "../assets/aud/All Them Witches - 41.mp3",
 "../assets/aud/All Them Witches - 6969 WXL THE CAGE.mp3",
"../assets/aud/All Them Witches - Alabaster.mp3",
"../assets/aud/All Them Witches - Am I Going Up.mp3",
"../assets/aud/All Them Witches - Blacksnake Blues.mp3",
"../assets/aud/All Them Witches - Blood And Sand  Milk And Endless Waters.mp3",
"../assets/aud/All Them Witches - Bruce Lee.mp3",
"../assets/aud/All Them Witches - Bulls.mp3",
"../assets/aud/All Them Witches - Call Me Star.mp3",
"../assets/aud/All Them Witches - Charles William.mp3",
"../assets/aud/All Them Witches - Cowboy Kirk.mp3",
"../assets/aud/All Them Witches - Diamond.mp3",
"../assets/aud/All Them Witches - Dirt Preachers.mp3",
"../assets/aud/All Them Witches - Elk.Blood.Heart.mp3",
"../assets/aud/All Them Witches - Enemy of My Enemy.mp3",
"../assets/aud/All Them Witches - Everest.mp3",
"../assets/aud/All Them Witches - Fall Into Place.mp3",
"../assets/aud/All Them Witches - Funeral For A Great Drunken Bird.mp3",
"../assets/aud/All Them Witches - HeavyLike a Witch.mp3",
"../assets/aud/All Them Witches - Holding Your Breath Across the River.mp3",
"../assets/aud/All Them Witches - Hush, I'm on TV.mp3",
"../assets/aud/All Them Witches - I Can't Even See Myself (Bonus).mp3",
"../assets/aud/All Them Witches - Internet.mp3",
"../assets/aud/All Them Witches - L'hotel Serein.mp3",
"../assets/aud/All Them Witches - Lights Out.mp3",
"../assets/aud/All Them Witches - Mellowing.mp3",
"../assets/aud/All Them Witches - Mountain.mp3",
"../assets/aud/All Them Witches - Open Passageways.mp3",
"../assets/aud/All Them Witches - Rats in Ruin.mp3",
"../assets/aud/All Them Witches - Real Hippies Are Cowboys.mp3",
"../assets/aud/All Them Witches - Romany Dagger (Remended).mp3",
"../assets/aud/All Them Witches - Saturnine & Iron Jaw.mp3",
"../assets/aud/All Them Witches - See You Next Fall.mp3",
"../assets/aud/All Them Witches - Slow City.mp3",
"../assets/aud/All Them Witches - Surface-To-Air Whistle.mp3",
"../assets/aud/All Them Witches - Swallowed By The Sea.mp3",
"../assets/aud/All Them Witches - Talisman.mp3",
"../assets/aud/All Them Witches - The Children of Coyote Woman.mp3",
"../assets/aud/All Them Witches - The Death Of Coyote Woman.mp3",
"../assets/aud/All Them Witches - The Marriage Of Coyote Woman.mp3",
"../assets/aud/All Them Witches - The Urn.mp3",
"../assets/aud/All Them Witches - When God Comes Back.mp3",
"../assets/aud/All Them Witches - Workhorse.mp3",
"../assets/aud/alt-J - Breezeblocks.mp3",
"../assets/aud/alt-J - Hunger of the Pine.mp3",
"../assets/aud/Amerie - Gotta Work.mp3",
"../assets/aud/Amigo the Devil - Dahmer Does Hollywood.mp3",
"../assets/aud/Amigo the Devil - The Liar's Club (Demo Version).mp3",
"../assets/aud/Amy Macdonald - This Is The Life.mp3",
"../assets/aud/Anderson .Paak, Jazmine Sullivan - Good Heels (feat. Jazmine Sullivan).mp3",
"../assets/aud/Andrew Bird - Minor Stab.mp3",
"../assets/aud/Andrew Gold - Spooky, Scary Skeletons.mp3",
"../assets/aud/Anna von Hausswolff - Mountains Crave.mp3",
"../assets/aud/Anna von Hausswolff - Old BeautyDu Kan Nu Dö.mp3",
"../assets/aud/Anna von Hausswolff - 'The Marble Eye' (Official Audio).mp3",
"../assets/aud/Anna von Hausswolff - The Mysterious Vanishing of Electra.mp3",
"../assets/aud/Anna von Hausswolff - The Truth, The Glow, The Fall.mp3",
"../assets/aud/Antonín Dvořák, Prague Chamber Orchestra, Petr Skvor - Serenade for Strings in E Major, Op. 22, B. 52 -  II. Tempo di valse.mp3",
"../assets/aud/Apparat, Soap&Skin - Goodbye.mp3",
"../assets/aud/Arcade Fire - My Body Is a Cage.mp3",
"../assets/aud/Ariana Grande - Into You.mp3",
"../assets/aud/Arlo Parks - Cola.mp3",
"../assets/aud/Ash Bricky - Chowchilla Song.mp3",
"../assets/aud/Ashanti - Rock Wit U (Awww Baby).mp3",
"../assets/aud/Ashnikko - Itty Bitty.mp3",
"../assets/aud/Astronaut - No Place for Lovers.mp3",
"../assets/aud/Ataraxia, Mort Garson - Deja Vu.mp3",
"../assets/aud/AuRa - Panic Room.mp3",
"../assets/aud/AURORA - Churchyard.mp3",
"../assets/aud/AURORA - Conqueror.mp3",
"../assets/aud/AURORA - Running With The Wolves.mp3",
"../assets/aud/AURORA - Soft Universe.mp3",
"../assets/aud/AURORA - The Seed.mp3",
"../assets/aud/AURORA - Under The Water.mp3",
"../assets/aud/AURORA - Warrior.mp3",
"../assets/aud/AURORA - Winter Bird.mp3",
"../assets/aud/AURORA, Pomme - Everything Matters.mp3",
"../assets/aud/AWOLNATION - Sail.mp3",
"../assets/aud/Baby Bash, Frankie J - Suga Suga.mp3",
"../assets/aud/Baby Charles - I Bet You Look Good On The Dancefloor.mp3",
"../assets/aud/Baby Charles - This Time.mp3",
"../assets/aud/Bad Brains - Banned in D.C..mp3",
"../assets/aud/Barns Courtney - Sinners.mp3",
"../assets/aud/Basement - Covet.mp3",
"../assets/aud/Basement Jaxx, Lisa Kekaula - Good Luck.mp3",
"../assets/aud/Bauhaus - All We Ever Wanted Was Everything.mp3",
"../assets/aud/Bauhaus - Bela Lugosi's Dead (Official Version).mp3",
"../assets/aud/Bauhaus - Dark Entries.mp3",
"../assets/aud/Bauhaus - Double Dare.mp3",
"../assets/aud/Bauhaus - Kick in the Eye.mp3",
"../assets/aud/Bauhaus - Lagartija Nick.mp3",
"../assets/aud/Bauhaus - Rosegarden Funeral of Sores.mp3",
"../assets/aud/Bauhaus - Telegram Sam.mp3",
"../assets/aud/Bauhaus - The Sanity Assassin.mp3",
"../assets/aud/Bauhaus - Ziggy Stardust.mp3",
"../assets/aud/Bazzi - Myself.mp3",
"../assets/aud/Be Mine.mp3",
"../assets/aud/Be My Baby.mp3",
"../assets/aud/Be Sweet.mp3",
"../assets/aud/Beardyman - Mountain Side.mp3",
"../assets/aud/Berlin - Take My Breath Away - Love Theme from 'Top Gun'.mp3",
"../assets/aud/Beyoncé - Irreplaceable.mp3",
"../assets/aud/Beyoncé, Bun B, Slim Thug - Check On It (feat. Bun B & Slim Thug).mp3",
"../assets/aud/Beyoncé, JAŸ-Z - Crazy In Love (feat. JAY-Z).mp3",
"../assets/aud/Bikini Kill - Rebel Girl.mp3",
"../assets/aud/Bill Withers - Lovely Day.mp3",
"../assets/aud/Billie Eilish - bury a friend.mp3",
"../assets/aud/Billie Eilish - Therefore I Am.mp3",
"../assets/aud/Billie Eilish - WHEN I WAS OLDER - Music Inspired By The Film ROMA.mp3",
"../assets/aud/Billie Eilish - you should see me in a crown.mp3",
"../assets/aud/Billy Idol - Eyes Without A Face.mp3",
"../assets/aud/Bishop Briggs - River.mp3",
"../assets/aud/Björk, Arca - Arisen My Senses.mp3",
"../assets/aud/Björk, Arca - Utopia.mp3",
"../assets/aud/Björk, Fever Ray - Features Creatures (Fever Ray Remix).mp3",
"../assets/aud/Black Lips - Boys in the Wood.mp3",
"../assets/aud/Black Ox Orkestar - Skocne.mp3",
"../assets/aud/Black Pistol Fire - Beelzebub.mp3",
"../assets/aud/Black Pistol Fire - So Real.mp3",
"../assets/aud/Black Pumas - Colors.mp3",
"../assets/aud/Black Rainbows - Waiting for the Sun.mp3",
"../assets/aud/Black Sabbath - Paranoid.mp3",
"../assets/aud/Blackstreet, Dr. Dre, Queen Pen - No Diggity.mp3",
"../assets/aud/Bleached - Wednesday Night Melody.mp3",
"../assets/aud/BLIND.SEE, Coreylte - Winning.mp3",
"../assets/aud/Blondie - One Way Or Another.mp3",
"../assets/aud/Blood Ceremony - Goodbye Gemini.mp3",
"../assets/aud/Bloom.mp3",
"../assets/aud/Blu Cantrell - Hit 'Em Up Style (Oops!).mp3",
"../assets/aud/Blue Denim.mp3",
"../assets/aud/Blue Öyster Cult - (Don't Fear) The Reaper.mp3",
"../assets/aud/Bobby 'Boris' Pickett, The Crypt-Kickers - Monster Mash.mp3",
"../assets/aud/Bobby 'Boris' Pickett, The Crypt-Kickers - Skully Gully.mp3",
"../assets/aud/Bohemian Rhapsody.mp3",
"../assets/aud/Bon Iver - Holocene.mp3",
"../assets/aud/Born for This.mp3",
"../assets/aud/Boy Harsher - Pain.mp3",
"../assets/aud/Brand New - Sic Transit Gloria ... Glory Fades.mp3",
"../assets/aud/Brant Bjork - Lazy Bones.mp3",
"../assets/aud/Breathe.mp3",
"../assets/aud/Brixton Briefcase.mp3",
"../assets/aud/Bronski Beat - Smalltown Boy.mp3",
"../assets/aud/Busta Rhymes, Mariah Carey, Flipmode Squad - I Know What You Want (feat. Flipmode Squad).mp3",
"../assets/aud/Cage The Elephant - Ain't No Rest For The Wicked - Original Version.mp3",
"../assets/aud/CAKE - Comfort Eagle.mp3",
"../assets/aud/Calvin Harris, Ellie Goulding - Outside (feat. Ellie Goulding).mp3",
"../assets/aud/Camille Saint-Saëns, Slovak Radio Symphony Orchestra, Keith Clark - Danse macabre in G Minor, Op. 40.mp3",
"../assets/aud/Caravan Palace - Black Betty.mp3",
"../assets/aud/Caravan Palace - Dramophone.mp3",
"../assets/aud/Caravan Palace - Lone Digger.mp3",
"../assets/aud/Caravan Palace - Moonshine - Chronometric Edit.mp3",
"../assets/aud/Caravan Palace - Wonderland.mp3",
"../assets/aud/Carly Rae Jepsen - Call Me Maybe.mp3",
"../assets/aud/Carly Rae Jepsen - Cut To The Feeling.mp3",
"../assets/aud/Carly Rae Jepsen - I Really Like You.mp3",
"../assets/aud/Carly Rae Jepsen - Party For One.mp3",
"../assets/aud/Carly Rae Jepsen - Run Away With Me.mp3",
"../assets/aud/Caroline Polachek - So Hot You're Hurting My Feelings.mp3",
"../assets/aud/Cass Elliot - Don't Let The Good Life Pass You By.mp3",
"../assets/aud/Cass Elliot - Make Your Own Kind Of Music.mp3",
"../assets/aud/Cassie - Long Way 2 Go.mp3",
"../assets/aud/Catch Your Death.mp3",
"../assets/aud/Cathedrals - In The Dark.mp3",
"../assets/aud/Cavetown - Boys Will Be Bugs.mp3",
"../assets/aud/Chaka Khan - I'm Every Woman.mp3",
"../assets/aud/Charlotte Day Wilson - Work.mp3",
"../assets/aud/Chelsea Wolfe  - After The Fall (Official Audio).mp3",
"../assets/aud/Chelsea Wolfe - Carrion Flowers (Official Audio).mp3",
"../assets/aud/Chelsea Wolfe - Deranged for Rock & Roll.mp3",
"../assets/aud/Chelsea Wolfe - Dragged Out (Official Audio).mp3",
"../assets/aud/Chelsea Wolfe - Dusk - Unbound.mp3",
"../assets/aud/Chelsea Wolfe - Dusk.mp3",
"../assets/aud/Chelsea Wolfe - Flatlands.mp3",
"../assets/aud/Chelsea Wolfe - Gold (Bonus Track).mp3",
"../assets/aud/Chelsea Wolfe - House of Metal.mp3",
"../assets/aud/Chelsea Wolfe - Iron Moon (Official Audio).mp3",
"../assets/aud/Chelsea Wolfe - Maw (Official Audio).mp3",
"../assets/aud/Chelsea Wolfe - Oui Oui Marie.mp3",
"../assets/aud/Chelsea Wolfe - Tunnel Lights.mp3",
"../assets/aud/Chelsea Wolfe - Twin Fawn.mp3",
"../assets/aud/Chelsea Wolfe - Whispers In The Echo Chamber (Official Music Video).mp3",
"../assets/aud/Chelsea Wolfe, Full Of Hell - Eyes Like Nightshade - Full Of Hell remix.mp3",
"../assets/aud/Childish Gambino - 3005.mp3",
"../assets/aud/Childish Gambino - Algorhythm.mp3",
"../assets/aud/Childish Gambino - Feels Like Summer.mp3",
"../assets/aud/Childish Gambino - Have Some Love.mp3",
"../assets/aud/Childish Gambino - Heartbeat.mp3",
"../assets/aud/Childish Gambino - IV. Sweatpants.mp3",
"../assets/aud/Childish Gambino - Redbone.mp3",
"../assets/aud/Childish Gambino - Sober.mp3",
"../assets/aud/Childish Gambino - That Power.mp3",
"../assets/aud/Childish Gambino - This Is America.mp3",
"../assets/aud/Childish Gambino, Brittany Howard - Stay High - Childish Gambino Version.mp3",
"../assets/aud/Chris Isaak - Wicked Game - Remastered.mp3",
"../assets/aud/Christina Aguilera - Fighter.mp3",
"../assets/aud/Christina Aguilera, Redman - Dirrty (feat. Redman).mp3",
"../assets/aud/Christopher Lee - The Devil's Advocate.mp3",
"../assets/aud/Clarence Clarity, Kill J - Buck-Toothed Particle Smashers.mp3",
"../assets/aud/Clothing Optional - Holy Darling.mp3",
"../assets/aud/Clothing Optional - Teen Rage.mp3",
"../assets/aud/Cocteau Twins - Aloysius.mp3",
"../assets/aud/Cocteau Twins - Amelia.mp3",
"../assets/aud/Cocteau Twins - Beatrix.mp3",
"../assets/aud/Cocteau Twins - Cicely.mp3",
"../assets/aud/Cocteau Twins - Donimo.mp3",
"../assets/aud/Cocteau Twins - Ivo.mp3",
"../assets/aud/Cocteau Twins - Lorelei.mp3",
"../assets/aud/Cocteau Twins - Otterley.mp3",
"../assets/aud/Cocteau Twins - Pandora (for Cindy).mp3",
"../assets/aud/Cocteau Twins - Persephone.mp3",
"../assets/aud/Cold (2022 Remaster).mp3",
"../assets/aud/Cold War Kids - Hang Me Up To Dry.mp3",
"../assets/aud/Colter Wall - Sleeping on the Blacktop.mp3",
"../assets/aud/Colter Wall - The Devil Wears a Suit and Tie.mp3",
"../assets/aud/Colter Wall - Thirteen Silver Dollars.mp3",
"../assets/aud/Cop Car.mp3",
"../assets/aud/Cosmo Sheldrake, HOWL - Does The Swallow Dream Of Flying.mp3",
"../assets/aud/Courtney Barnett - Anonymous Club.mp3",
"../assets/aud/Courtney Barnett - Avant Gardener.mp3",
"../assets/aud/Courtney Barnett - History Eraser.mp3",
"../assets/aud/Courtney Barnett - Nameless, Faceless.mp3",
"../assets/aud/Courtney Barnett - Scotty Says.mp3",
"../assets/aud/Crazy Monkey - lofi circus - Entry of the Gladiators.mp3",
"../assets/aud/Crazy Monkey - lofi circus II - Stars and Stripes Forever.mp3",
"../assets/aud/Crazy Monkey - Merry Go Round I (lofi circus).mp3",
"../assets/aud/Crazy Monkey - Merry Go Round IV (lofi circus).mp3",
"../assets/aud/Crazy On You.mp3",
"../assets/aud/Cream - White Room.mp3",
"../assets/aud/Creed - Higher (Remastered) (Official Audio).mp3",
"../assets/aud/Creed - One Last Breath.mp3",
"../assets/aud/Creed - With Arms Wide Open (Remastered) (Official Audio).mp3",
"../assets/aud/Creedence Clearwater Revival - Bad Moon Rising.mp3",
"../assets/aud/Creep.mp3",
"../assets/aud/crushcrushcrush.mp3",
"../assets/aud/Cut Hands.mp3",
"../assets/aud/CXZ.mp3",
"../assets/aud/Daijobu Desu.mp3",
"../assets/aud/Danger Zone.mp3",
"../assets/aud/DANGERDOOM, MF DOOM, Danger Mouse, CeeLo Green - Benzi Box.mp3",
"../assets/aud/Daniela Lalita - Atrás.mp3",
"../assets/aud/Daniela Lalita - Tenía Razón.mp3",
"../assets/aud/Daniela Lalita - Trececerotres.mp3",
"../assets/aud/Danit, Rey&Kjavik - Cuatro Vientos - Rey&Kjavik Remix.mp3",
"../assets/aud/Dark Rooms - 6am & Do It Again.mp3",
"../assets/aud/Dave Van Ronk - Hang Me, Oh Hang Me.mp3",
"../assets/aud/David Bowie - Blackstar.mp3",
"../assets/aud/David Bowie - Cat People (Putting out Fire).mp3",
"../assets/aud/David Bowie - Changes - 2015 Remaster.mp3",
"../assets/aud/David Bowie - Life on Mars - 2015 Remaster.mp3",
"../assets/aud/David Bowie - Moonage Daydream - 2012 Remaster.mp3",
"../assets/aud/David Bowie - Space Oddity - 2015 Remaster.mp3",
"../assets/aud/David Bowie - Ziggy Stardust - 2012 Remastered Version.mp3",
"../assets/aud/Dead Man's Bones - Werewolf Heart.mp3",
"../assets/aud/Deee-Lite - Groove Is in the Heart.mp3",
"../assets/aud/Deftones - Change (In the House of Flies).mp3",
"../assets/aud/deftones - milk of the madonna [visualizer].mp3",
"../assets/aud/Deftones - My Own Summer (Shove It).mp3",
"../assets/aud/Departing The Body.mp3",
"../assets/aud/Desert Sessions - If You Run.mp3",
"../assets/aud/Desire - Under Your Spell.mp3",
"../assets/aud/Desireless - Voyage voyage.mp3",
"../assets/aud/Destroy Boys - American River.mp3",
"../assets/aud/Devault, Izzy Camina - HEAVEN'S GATES (feat. Izzy Camina).mp3",
"../assets/aud/Devil's Train.mp3",
"../assets/aud/Dick Dale - Misirlou.mp3",
"../assets/aud/Digital Bath.mp3",
"../assets/aud/Dilemma.mp3",
"../assets/aud/Dip It Low.mp3",
"../assets/aud/DIR EN GREY - Lotus.mp3",
"../assets/aud/Dire Straits - Walk Of Life.mp3",
"../assets/aud/DJ Fresh, SHY FX - Gold Dust - SHY FX Re-Edit.mp3",
"../assets/aud/Dj Meetha - Sugar How You Get So Fly.mp3",
"../assets/aud/Dlina Volny - Whatever Happens Next.mp3",
"../assets/aud/Doechii - Doechii 101.mp3",
"../assets/aud/Doechii - MPH.mp3",
"../assets/aud/Doechii - Nosebleeds.mp3",
"../assets/aud/Doechii - Pacer.mp3",
"../assets/aud/Doechii - ROCKET.mp3",
"../assets/aud/Doechii, KAYTRANADA, JT - Alter Ego (KAYTRANADA Remix)[with JT].mp3",
"../assets/aud/Dolly Parton - 9 to 5.mp3",
"../assets/aud/Dolly Parton - Baby I'm Burnin'.mp3",
"../assets/aud/Dolly Parton - Holly Jolly Christmas.mp3",
"../assets/aud/Dolly Parton - Jolene.mp3",
"../assets/aud/Dolly Parton - Light of a Clear Blue Morning.mp3",
"../assets/aud/Dolly Parton - Silver Dagger.mp3",
"../assets/aud/Dolly Parton, Linda Ronstadt, Emmylou Harris - Wildflowers.mp3",
"../assets/aud/Domkraft - Drones.mp3",
"../assets/aud/Donovan - Bert's Blues.mp3",
"../assets/aud/Donovan - Hurdy Gurdy Man.mp3",
"../assets/aud/Donovan - Season of the Witch (2005 Remastered Version) [Mono].mp3",
"../assets/aud/Doombop.mp3",
"../assets/aud/DOPE LEMON - Hey Little Baby.mp3",
"../assets/aud/Dowry - In É.mp3",
"../assets/aud/Dreamer Isioma - Sensitive.mp3",
"../assets/aud/Dry the River - Shaker Hymns.mp3",
"../assets/aud/Dusty Springfield - Spooky.mp3",
"../assets/aud/Dynoro, Gigi D'Agostino - In My Mind.mp3",
"../assets/aud/E.D. Kadence - TRIP ON THE PARTY BUS - DRUNK DEMO.mp3",
"../assets/aud/Eagles Of Death Metal - Blinded By The Light - From  Super Troopers 2  Soundtrack.mp3",
"../assets/aud/Eats The Tale (Edit).mp3",
"../assets/aud/Ecdysis.mp3",
"../assets/aud/Echo & the Bunnymen - The Killing Moon.mp3",
"../assets/aud/Eleanor Rigby.mp3",
"../assets/aud/Electric Wizard - Electric Wizard.mp3",
"../assets/aud/Elite.mp3",
"../assets/aud/Elizabeth Cotten - I'm Going Away.mp3",
"../assets/aud/Emei - Scatterbrain.mp3",
"../assets/aud/Emma Peters - Clandestina - Version acoustique.mp3",
"../assets/aud/Emma Ruth Rundle - Marked for Death.mp3",
"../assets/aud/Emotion.mp3",
"../assets/aud/Erik Satie, Alexandre Tharaud - Gnossienne- No. 1.mp3",
"../assets/aud/Ethel Cain - A House In Nebraska.mp3",
"../assets/aud/Ethel Cain - American Teenager.mp3",
"../assets/aud/Ethel Cain - August Underground.mp3",
"../assets/aud/Ethel Cain - Family Tree (Intro).mp3",
"../assets/aud/Ethel Cain - Family Tree.mp3",
"../assets/aud/Ethel Cain - Gibson Girl.mp3",
"../assets/aud/Ethel Cain - Hard Times.mp3",
"../assets/aud/Ethel Cain - Ptolemaea.mp3",
"../assets/aud/Ethel Cain - Strangers.mp3",
"../assets/aud/Ethel Cain - Sun Bleached Flies.mp3",
"../assets/aud/Ethel Cain - Televangelism.mp3",
"../assets/aud/Ethel Cain - Thoroughfare.mp3",
"../assets/aud/Ethel Cain - Western Nights.mp3",
"../assets/aud/Etta James - Something's Got A Hold On Me - Single Version.mp3",
"../assets/aud/Eve - Who's That Girl.mp3",
"../assets/aud/Everything Turns Blue.mp3",
"../assets/aud/Everything You Needed.mp3",
"../assets/aud/Everywhere.mp3",
"../assets/aud/Exuma - Dambala.mp3",
"../assets/aud/Fabienne DelSol - I'm Gonna Haunt You.mp3",
"../assets/aud/Faithless - Insomnia (Lyrics).mp3",
"../assets/aud/Fall Out Boy - 'The Take Over, The Breaks Over'.mp3",
"../assets/aud/Fall Out Boy - Young And Menace.mp3",
"../assets/aud/Fat Joe, Ja Rule, Ashanti - What's Luv (feat. Ja-Rule & Ashanti).mp3",
"../assets/aud/Father John Misty - Hollywood Forever Cemetery Sings.mp3",
"../assets/aud/Father John Misty - I'm Writing a Novel.mp3",
"../assets/aud/Feiticeira.mp3",
"../assets/aud/Fences.mp3",
"../assets/aud/Fever Ray - Here Before.mp3",
"../assets/aud/Fever Ray - When I Grow Up.mp3",
"../assets/aud/Fever Ray 'If I Had A Heart'.mp3",
"../assets/aud/Ffrancis - What If a Lightning Struck You.mp3",
"../assets/aud/Filter - Hey Man, Nice Shot - Remastered Version 2025.mp3",
"../assets/aud/Fiona Apple - Fetch The Bolt Cutters.mp3",
"../assets/aud/Fiona Apple - Hot Knife.mp3",
"../assets/aud/FKA twigs - cellophane.mp3",
"../assets/aud/FKA twigs - Eusexua.mp3",
"../assets/aud/FKA twigs - fallen alien.mp3",
"../assets/aud/FKA twigs - Figure 8.mp3",
"../assets/aud/FKA twigs - In Time.mp3",
"../assets/aud/FKA twigs - mary magdalene.mp3",
"../assets/aud/FKA twigs - mirrored heart.mp3",
"../assets/aud/FKA twigs - Pendulum.mp3",
"../assets/aud/FKA twigs - thousand eyes.mp3",
"../assets/aud/FKA twigs - Two Weeks.mp3",
"../assets/aud/FLAVIA - Them.mp3",
"../assets/aud/Fleetwood Mac - Everywhere.mp3",
"../assets/aud/Fleetwood Mac - Gold Dust Woman - 2004 Remaster.mp3",
"../assets/aud/Fleetwood Mac - Landslide.mp3",
"../assets/aud/Fleetwood Mac - Never Going Back Again - Live 1977.mp3",
"../assets/aud/Fleetwood Mac - Silver Springs - 2004 Remaster.mp3",
"../assets/aud/Fleetwood Mac - Sisters of the Moon - 2015 Remaster.mp3",
"../assets/aud/Fleetwood Mac - The Chain - 2004 Remaster.mp3",
"../assets/aud/FLETCHER - Becky’s So Hot.mp3",
"../assets/aud/Florence + The Machine - Big God.mp3",
"../assets/aud/Florence + The Machine - Cosmic Love.mp3",
"../assets/aud/Florence + The Machine - Dog Days Are Over.mp3",
"../assets/aud/Florence + The Machine - Dream Girl Evil.mp3",
"../assets/aud/Florence + The Machine - King.mp3",
"../assets/aud/Florence + The Machine - Kiss With A Fist.mp3",
"../assets/aud/Florence + The Machine - Spectrum (Say My Name).mp3",
"../assets/aud/Florence + The Machine - What The Water Gave Me.mp3",
"../assets/aud/Florence + The Machine - Which Witch.mp3",
"../assets/aud/Flying Lotus, Thundercat - Descent Into Madness.mp3",
"../assets/aud/Focus - Hocus Pocus - Extended Version.mp3",
"../assets/aud/Foo Fighters - Best of You.mp3",
"../assets/aud/Foolish.mp3",
"../assets/aud/For a Pessimist, I'm Pretty Optimistic.mp3",
"../assets/aud/Forest Swords - Friend, You Will Never Learn.mp3",
"../assets/aud/Forest Swords - Panic.mp3",
"../assets/aud/Forest Swords - Thor's Stone.mp3",
"../assets/aud/Fousheé - Deep End.mp3",
"../assets/aud/Frances Forever - Space Girl.mp3",
"../assets/aud/Frank Ocean - Lost.mp3",
"../assets/aud/Franz Liszt, Jenő Jandó - Liebestraume, S541R211  -  No. 3 -  Nocturne in A-Flat Major.mp3",
"../assets/aud/Fugazi - I'm So Tired.mp3",
"../assets/aud/Fun Lovin' Criminals - I Can't Get with That.mp3",
"../assets/aud/Funkadelic - Can You Get To That.mp3",
"../assets/aud/Funkadelic - Maggot Brain.mp3",
"../assets/aud/Funnel Of Love.mp3",
"../assets/aud/Gatekeeper - Chains.mp3",
"../assets/aud/Gatekeeper - Giza.mp3",
"../assets/aud/Gatekeeper - Mirage.mp3",
"../assets/aud/Gatekeeper - Oracle.mp3",
"../assets/aud/Gatekeeper - Serpent.mp3",
"../assets/aud/Gatekeeper - Storm Column.mp3",
"../assets/aud/Gay For Johnny Depp - Belief in God Is so Adorable.mp3",
"../assets/aud/Gay For Johnny Depp - She Said 'I Like This One.'.mp3",
"../assets/aud/Gay For Johnny Depp - Shh, Put the Shiv to My Throat.mp3",
"../assets/aud/Gay Girls.mp3",
"../assets/aud/Genghis Khan.mp3",
"../assets/aud/Gimme All Your Love.mp3",
"../assets/aud/Gipsy Kings - Bamboléo.mp3",
"../assets/aud/girl in red - bad idea!.mp3",
"../assets/aud/Glüme - Santa Baby.mp3",
"../assets/aud/Godspeed You! Black Emperor - Storm.mp3",
"../assets/aud/Godspeed You! Black Emperor - The Dead Flag Blues.mp3",
"../assets/aud/Gogol Bordello - Wonderlust King.mp3",
"../assets/aud/Gomugomu.mp3",
"../assets/aud/Good Luck Babe.mp3",
"../assets/aud/Gorillaz, De La Soul - Feel Good Inc..mp3",
"../assets/aud/Gorillaz, Del The Funky Homosapien - Clint Eastwood.mp3",
"../assets/aud/Gorillaz, Del The Funky Homosapien - Rock the House.mp3",
"../assets/aud/Gorillaz, George Benson - Humility (feat. George Benson).mp3",
"../assets/aud/Gorillaz, Miho Hatori, Tina Weymouth - 19-2000.mp3",
"../assets/aud/Gossip - Standing In the Way of Control.mp3",
"../assets/aud/Grails - Smokey Room.mp3",
"../assets/aud/Grateful Dead - Truckin' - 2020 Remaster.mp3",
"../assets/aud/Green Day - Jesus of Suburbia (Official Audio).mp3",
"../assets/aud/Grover Washington, Jr., Bill Withers - Just the Two of Us (feat. Bill Withers).mp3",
"../assets/aud/Gustavo Bravetti - Babel.mp3",
"../assets/aud/Haley Heynderickx, Max García Conover - Francis.mp3",
"../assets/aud/Hallelujah.mp3",
"../assets/aud/Halsey - Ghost.mp3",
"../assets/aud/Hans Zimmer - S.T.A.Y..mp3",
"../assets/aud/Harry Belafonte - Jump in the Line (Shake, Senora).mp3",
"../assets/aud/HARU NEMURI - kick in the world.mp3",
"../assets/aud/He Is We - I Wouldn't Mind.mp3",
"../assets/aud/Head Automatica - Beating Heart Baby.mp3",
"../assets/aud/Head Like A Hole.mp3",
"../assets/aud/HEALTH - FEEL NOTHING.mp3",
"../assets/aud/Heavy.mp3",
"../assets/aud/Helplessly Hoping.mp3",
"../assets/aud/Hermanos Gutiérrez - Cerca De Ti.mp3",
"../assets/aud/Hermanos Gutiérrez - El Desierto.mp3",
"../assets/aud/Hippie Sabotage - Trust Nobody.mp3",
"../assets/aud/HMLTD - Satan, Luella & I.mp3",
"../assets/aud/Holiday in Cambodia.mp3",
"../assets/aud/Holly Herndon - Frontier.mp3",
"../assets/aud/Hollywood.mp3",
"../assets/aud/Holy_Til_You_Let_Me_Go.mp3",
"../assets/aud/House Of Pain - Jump Around.mp3",
"../assets/aud/How I'd Kill.mp3",
"../assets/aud/Hoy Como Ayer.mp3",
"../assets/aud/Hozier - Almost (Sweet Music).mp3",
"../assets/aud/Hozier - Angel Of Small Death & The Codeine Scene.mp3",
"../assets/aud/Hozier - Arsonist's Lullabye.mp3",
"../assets/aud/Hozier - As It Was.mp3",
"../assets/aud/Hozier - Be.mp3",
"../assets/aud/Hozier - Dinner & Diatribes.mp3",
"../assets/aud/Hozier - Do I Wanna Know - Live At the BBC.mp3",
"../assets/aud/Hozier - Empire Now.mp3",
"../assets/aud/Hozier - From Eden.mp3",
"../assets/aud/Hozier - Hymn To Virgil.mp3",
"../assets/aud/Hozier - In The Woods Somewhere.mp3",
"../assets/aud/Hozier - It Will Come Back.mp3",
"../assets/aud/Hozier - Jackie And Wilson.mp3",
"../assets/aud/Hozier - Like Real People Do.mp3",
"../assets/aud/Hozier - NFWMB.mp3",
"../assets/aud/Hozier - No Plan.mp3",
"../assets/aud/Hozier - Nobody.mp3",
"../assets/aud/Hozier - Nobody's Soldier (Official Lyric Video) (1).mp3",
"../assets/aud/Hozier - Shrike.mp3",
"../assets/aud/Hozier - Sunlight.mp3",
"../assets/aud/Hozier - Take Me To Church.mp3",
"../assets/aud/Hozier - Talk.mp3",
"../assets/aud/Hozier - The Parting Glass - Live from the Late Late Show.mp3",
"../assets/aud/Hozier - To Be Alone.mp3",
"../assets/aud/Hozier - To Noise Making (Sing).mp3",
"../assets/aud/Hozier - Wasteland, Baby!.mp3",
"../assets/aud/Hozier - Work Song.mp3",
"../assets/aud/Hozier - Would That I.mp3",
"../assets/aud/Humanwine - Rivolta Silenziosa.mp3",
"../assets/aud/Hus KingPin, Westside Gunn, Manny Megz - Victims of Vogue - Cocaine in Bourdeaux Remix.mp3",
"../assets/aud/I Monster - Daydream In Blue.mp3",
"../assets/aud/i think about you all the time.mp3",
"../assets/aud/iamamiwhoami - Play.mp3",
"../assets/aud/iamamiwhoami, ionnalee - chasing kites.mp3",
"../assets/aud/Ice Cream.mp3",
"../assets/aud/Igbal Jogi and Party - Lal Mori Pat.mp3",
"../assets/aud/Igbal Jogi and Party - Momil Rano.mp3",
"../assets/aud/Ikey - Story Story.mp3",
"../assets/aud/Ikey - Theone Song.mp3",
"../assets/aud/Illinformed, B-Va, Leaf Dog - Back Down (feat. Bva & Leaf Dog).mp3",
"../assets/aud/I'm On Fire.mp3",
"../assets/aud/In Your Eyes.mp3",
"../assets/aud/Incubus - Drive.mp3",
"../assets/aud/Incubus - Out From Under (LyricsSub Español) (HD).mp3",
"../assets/aud/Incubus - Pardon Me.mp3",
"../assets/aud/Infinite Source.mp3",
"../assets/aud/INTERWORLD - METAMORPHOSIS - Sped Up.mp3",
"../assets/aud/INXS - Never Tear Us Apart.mp3",
"../assets/aud/Iron & Wine - Autumn Town Leaves.mp3",
"../assets/aud/itchy-O - Chontaré - Original.mp3",
"../assets/aud/itchy-O - Diakkas.mp3",
"../assets/aud/itchy-O - Nefratata.mp3",
"../assets/aud/itchy-O - Pole Star.mp3",
"../assets/aud/itchy-O - The Silver River.mp3",
"../assets/aud/J. Cole, Cults, Amber Coffman - She Knows (feat. Amber Coffman & Cults).mp3",
"../assets/aud/Ja Rule, Case - Livin' It Up.mp3",
"../assets/aud/Jack Stauber - Oh Klahoma.mp3",
"../assets/aud/Jackie Venson - Witchcraft.mp3",
"../assets/aud/Jackie Wilson - (Your Love Keeps Lifting Me) Higher & Higher.mp3",
"../assets/aud/Jade Bird - Cathedral.mp3",
"../assets/aud/James Blake - Retrograde.mp3",
"../assets/aud/James Gang - Funk #49.mp3",
"../assets/aud/James Gang - Walk Away.mp3",
"../assets/aud/Jamiroquai - Little L.mp3",
"../assets/aud/Je te laisserai des mots.spotdlTrackingFile",
"../assets/aud/Jefferson Airplane - Somebody to Love.mp3",
"../assets/aud/Jefferson Airplane - Today.mp3",
"../assets/aud/Jefferson Airplane - White Rabbit.mp3",
"../assets/aud/Jennifer Lopez - Get Right.mp3",
"../assets/aud/Jesse Jo Stark - Fire of Love.mp3",
"../assets/aud/Joan Baez - Diamonds And Rust.mp3",
"../assets/aud/Joan Baez - Donna Donna.mp3",
"../assets/aud/Joan Baez - East Virginia.mp3",
"../assets/aud/Joan Baez - El Preso Numero Nueve.mp3",
"../assets/aud/Joan Baez - Fare Thee Well.mp3",
"../assets/aud/Joan Baez - Girl Of Constant Sorrow.mp3",
"../assets/aud/Joan Baez - House Of The Rising Sun.mp3",
"../assets/aud/Joan Baez - I Know You Rider.mp3",
"../assets/aud/Joan Baez - Rake And Rambling Boy.mp3",
"../assets/aud/Joan Baez - Wildwood Flower.mp3",
"../assets/aud/Johanna.mp3",
"../assets/aud/John Zacherle - Happy Halloween.mp3",
"../assets/aud/Johnny Cash - Big Iron.mp3",
"../assets/aud/Johnny Cash - God's Gonna Cut You Down.mp3",
"../assets/aud/Johnny Otis - Casting My Spell.mp3",
"../assets/aud/José Feliciano - Feliz Navidad.mp3",
"../assets/aud/Joy Oladokun - breathe again.mp3",
"../assets/aud/Joywave - Destruction.mp3",
"../assets/aud/Judy Henske - High Flying Bird.mp3",
"../assets/aud/Julia Romana - Blood Be Fluid.mp3",
"../assets/aud/Jung Kook - Standing Next to You.mp3",
"../assets/aud/Jungle - Back On 74.mp3",
"../assets/aud/Jungle - Let's Go Back.mp3",
"../assets/aud/Junior dos Santos Silva - Moonlight Sonata (1st Movement).mp3",
"../assets/aud/Justin Timberlake - Señorita.mp3",
"../assets/aud/K.Flay - Blood In The Cut.mp3",
"../assets/aud/Kaiit - Miss Shiney.mp3",
"../assets/aud/Kaiit - OG Luv Kush.mp3",
"../assets/aud/Kaleida - Think.mp3",
"../assets/aud/KALEO _Broken Bones_ [Official Audio].mp3",
"../assets/aud/Kanye West, Syleena Johnson - All Falls Down.mp3",
"../assets/aud/Kardinal Offishall - Mic T.H.U.G.S..mp3",
"../assets/aud/Kardinal Offishall, Emanuel, Jully Black, Savannah Ré, Susan Carol - Freedom Heights (A Song For Joshua Glover).mp3",
"../assets/aud/Kate Bush - Babooshka.mp3",
"../assets/aud/Kate Bush - Running Up That Hill (A Deal With God).mp3",
"../assets/aud/Katzenjammer - Hey Ho On the Devil's Back.mp3",
"../assets/aud/Kavinsky - Nightcall.mp3",
"../assets/aud/Keep On Talking To Yourself.mp3",
"../assets/aud/Kehlani - Gangsta.mp3",
"../assets/aud/Kehlani - Honey.mp3",
"../assets/aud/Kelis - Caught Out There.mp3",
"../assets/aud/Kelis - Trick Me.mp3",
"../assets/aud/Kelis, André 3000 - Millionaire.mp3",
"../assets/aud/Kelly Clarkson - Miss Independent.mp3",
"../assets/aud/Kelly Clarkson - Since U Been Gone.mp3",
"../assets/aud/Keysha Freshh - Rambos Freestyle.mp3",
"../assets/aud/Kikagaku Moyo - Dancing Blue.mp3",
"../assets/aud/Kikagaku Moyo - Daydream Soda.mp3",
"../assets/aud/Kikagaku Moyo - Dripping Sun.mp3",
"../assets/aud/Kikagaku Moyo - Dune.mp3",
"../assets/aud/Kikagaku Moyo - Effe.mp3",
"../assets/aud/Kikagaku Moyo - Field of Tiger Lilies.mp3",
"../assets/aud/Kikagaku Moyo - Gatherings.mp3",
"../assets/aud/Kikagaku Moyo - Hem.mp3",
"../assets/aud/Kikagaku Moyo - Kodama.mp3",
"../assets/aud/Kikagaku Moyo - Monaka.mp3",
"../assets/aud/Kikagaku Moyo - Old Snow, White Sun.mp3",
"../assets/aud/Kikagaku Moyo - Semicircle.mp3",
"../assets/aud/Kikagaku Moyo - Yayoi, Iyayoi.mp3",
"../assets/aud/Kim Mitchell - Go For Soda.mp3",
"../assets/aud/Kim Petras - Heart to Break.mp3",
"../assets/aud/King Gizzard & The Lizard Wizard - Fishing For Fishies - 01 Fishing For Fishies.mp3",
"../assets/aud/King Gizzard & The Lizard Wizard - Fishing For Fishies - 02 Boogieman Sam.mp3",
"../assets/aud/King Gizzard & The Lizard Wizard - Fishing For Fishies - 03 The Bird Song.mp3",
"../assets/aud/King Gizzard & The Lizard Wizard - Fishing For Fishies - 04 Plastic Boogie.mp3",
"../assets/aud/King Gizzard & The Lizard Wizard - Fishing For Fishies - 05 The Cruel Millennial.mp3",
"../assets/aud/King Gizzard & The Lizard Wizard - Fishing For Fishies - 06 Real's Not Real.mp3",
"../assets/aud/King Gizzard & The Lizard Wizard - Fishing For Fishies - 07 This Thing.mp3",
"../assets/aud/King Gizzard & The Lizard Wizard - Fishing For Fishies - 08 Acarine.mp3",
"../assets/aud/King Gizzard & The Lizard Wizard - Fishing For Fishies - 09 Cyboogie.mp3",
"../assets/aud/King Gizzard & The Lizard Wizard - Phantom Island - 01 Phantom Island.mp3",
"../assets/aud/King Gizzard & The Lizard Wizard - Phantom Island - 02 Deadstick.mp3",
"../assets/aud/King Gizzard & The Lizard Wizard - Phantom Island - 03 Lonely Cosmos.mp3",
"../assets/aud/King Gizzard & The Lizard Wizard - Phantom Island - 04 Eternal Return.mp3",
"../assets/aud/King Gizzard & The Lizard Wizard - Phantom Island - 05 Panpsych.mp3",
"../assets/aud/King Gizzard & The Lizard Wizard - Phantom Island - 06 Spacesick.mp3",
"../assets/aud/King Gizzard & The Lizard Wizard - Phantom Island - 07 Aerodynamic.mp3",
"../assets/aud/King Gizzard & The Lizard Wizard - Phantom Island - 08 Sea of Doubt.mp3",
"../assets/aud/King Gizzard & The Lizard Wizard - Phantom Island - 09 Silent Spirit.mp3",
"../assets/aud/King Gizzard & The Lizard Wizard - Phantom Island - 10 Grow Wings and Fly.mp3",
"../assets/aud/Knife Prty.mp3",
"../assets/aud/Korea.mp3",
"../assets/aud/Korn - Coming Undone.mp3",
"../assets/aud/Korn - Falling Away from Me (Lyrics).mp3",
"../assets/aud/Korn - Freak On a Leash.mp3",
"../assets/aud/Korn - Here To Stay.mp3",
"../assets/aud/Krzysztof Penderecki, Cracow Philharmonic Orchestra, Wojciech Czepiel - Threnody to the Victims of Hiroshima.mp3",
"../assets/aud/Kurt Vile - Pretty Pimpin.mp3",
"../assets/aud/Labrinth - Forever.mp3",
"../assets/aud/Labrinth - Mount Everest.mp3",
"../assets/aud/Labrinth, Zendaya - All For Us.mp3",
"../assets/aud/Labrinth, Zendaya - I’m Tired (with Zendaya) - Bonus Track.mp3",
"../assets/aud/Lady Gaga - Diamond Heart.mp3",
"../assets/aud/Lady Gaga - Grigio Girls.mp3",
"../assets/aud/Lady Gaga - John Wayne.mp3",
"../assets/aud/Latch.mp3",
"../assets/aud/Laura Marling - Devil's Resting Place.mp3",
"../assets/aud/Le Tigre - Deceptacon.mp3",
"../assets/aud/Le Tigre - Phanta.mp3",
"../assets/aud/Led Zeppelin - Immigrant Song - Remaster.mp3",
"../assets/aud/Led Zeppelin - Stairway to Heaven - Remaster.mp3",
"../assets/aud/Left at London - Revolution Lover.mp3",
"../assets/aud/Léo Delibes, Dame Joan Sutherland, Jane Berbié, Monte-Carlo Philharmonic Orchestra, Richard Bonynge - Lakmé  Act 1 -  Viens, Mallika, ... Dôme épais.mp3",
"../assets/aud/L'Epee - Dreams.mp3",
"../assets/aud/Lesley Gore - You Don't Own Me.mp3",
"../assets/aud/Let the Flames Begin.mp3",
"../assets/aud/L'FREAQ - Gimmick.mp3",
"../assets/aud/Liam Lynch - United States Of Whatever.mp3",
"../assets/aud/Lil Nas X - MONTERO (Call Me By Your Name).mp3",
"../assets/aud/Link Wray - Rumble.mp3",
"../assets/aud/Lisa LeBlanc - You Look Like Trouble (But I Guess I Do Too).mp3",
"../assets/aud/Locked Club.mp3",
"../assets/aud/Lorde - Green Light.mp3",
"../assets/aud/Lorn - Acid Rain.mp3",
"../assets/aud/Lorn - Anvil.mp3",
"../assets/aud/Lorn - Conduit.mp3",
"../assets/aud/Love Alive.mp3",
"../assets/aud/Love Is Like A Butterfly.mp3",
"../assets/aud/Love Will Tear Us Apart.mp3",
"../assets/aud/Low Roar - Breathe In.mp3",
"../assets/aud/Lowkey - Long Live Palestine.mp3",
"../assets/aud/Lunachicks - Dear Dotti.mp3",
"../assets/aud/Lunachicks - Don't Want You.mp3",
"../assets/aud/LYELL - Eraser.mp3",
"../assets/aud/Lynyrd Skynyrd - Free Bird.mp3",
"../assets/aud/machineheart - Overgrown.mp3",
"../assets/aud/Mad Within Reason.mp3",
"../assets/aud/Madcon - Beggin (original version).mp3",
"../assets/aud/Madness - Baggy Trousers.mp3",
"../assets/aud/Madness - House of Fun.mp3",
"../assets/aud/Madness - One Step Beyond.mp3",
"../assets/aud/Madonna - Like a Prayer.mp3",
"../assets/aud/Magic Man.mp3",
"../assets/aud/MaJLo - Escape.mp3",
"../assets/aud/Mama Is A Shining Star.mp3",
"../assets/aud/Mannequin Pussy - Romantic.mp3",
"../assets/aud/Mariah Carey - Fantasy.mp3",
"../assets/aud/Marin Marais, Ensemble Fitzwilliam, Pascal Monteilhet - Pièces de viole, Livre IV, Suite d'un goût étranger.mp3",
"../assets/aud/Marin Marais, Johanna Rose, Josep Maria Martí Duran, Javier Nuñez - Pièces de viole, Livre V- XVI. Prélude en Harpègement.mp3",
"../assets/aud/Marin Marais, Jordi Savall, Hopkinson Smith, Ton Koopman - Pièces de viole du Quatrième Livre, suite d’un goût étranger- La Rêveuse, IV. 82 (1711).mp3",
"../assets/aud/Marin Marais, Mieneke van der Velden, Glen Wilson - Allemenade la Superbe (4e livre)- La Rêveuse (4e livre).mp3",
"../assets/aud/Marin Marais, Mieneke van der Velden, Glen Wilson - Allemenade la Superbe (4e livre).mp3",
"../assets/aud/Marin Marais, Sophie Watillon, Friederike Heumann, Xavier Diaz-Latorre, Luca Guglielmi - 5e livre de viole -  Prélude en harpègement -  rondement.mp3",
"../assets/aud/Mark Korven - Witch's Coven.mp3",
"../assets/aud/Marlon Williams - Dark Child.mp3",
"../assets/aud/Marriages - Skin.mp3",
"../assets/aud/Martha Wainwright - Proserpina.mp3",
"../assets/aud/Massive Attack, Hope Sandoval - Paradise Circus.mp3",
"../assets/aud/Massive Attack, Young Fathers - Voodoo In My Blood.mp3",
"../assets/aud/Meat Wave - That's Alright.mp3",
"../assets/aud/MEDUZA, Becky Hill, Goodboys - Lose Control.mp3",
"../assets/aud/MEG MYERS - Running Up That Hill.mp3",
"../assets/aud/Megan Thee Stallion - Her.mp3",
"../assets/aud/Mesa Redonda.mp3",
"../assets/aud/metal dream.mp3",
"../assets/aud/Metro Boomin, The Weeknd, 21 Savage - Creepin.mp3",
"../assets/aud/MGMT - Electric Feel.mp3",
"../assets/aud/MGMT - Little Dark Age.mp3",
"../assets/aud/MGMT - When You Die.mp3",
"../assets/aud/Michael Jackson - Thriller.mp3",
"../assets/aud/Michael Jackson - You Rock My World.mp3",
"../assets/aud/MICRO-ONDES - More Guns.mp3",
"../assets/aud/Mikolai Stroinski - The Wolf And The Swallow.mp3",
"../assets/aud/Mild Orange - Losing Time.mp3",
"../assets/aud/Miley Cyrus - I Would Die For You.mp3",
"../assets/aud/Miley Cyrus - Midnight Sky.mp3",
"../assets/aud/Miley Cyrus - See You Again.mp3",
"../assets/aud/Miley Cyrus - Younger Now.mp3",
"../assets/aud/Miley Cyrus, Stevie Nicks - Edge of Midnight (Midnight Sky Remix) (feat. Stevie Nicks).mp3",
"../assets/aud/Mindless Self Indulgence - Shut Me Up.mp3",
"../assets/aud/Minnie Riperton - Les Fleurs.mp3",
"../assets/aud/Minnie The Moocher.mp3",
"../assets/aud/Miracle.mp3",
"../assets/aud/Misery Business (Acoustic Version).mp3",
"../assets/aud/Misery Business.mp3",
"../assets/aud/Mitski - Your Best American Girl.mp3",
"../assets/aud/MNDR, TOKiMONSTA - We Love (feat. MNDR).mp3",
"../assets/aud/Mocking Bird.mp3",
"../assets/aud/Molchat Doma - Судно (Борис Рижий).mp3",
"../assets/aud/Moment's Silce.mp3",
"../assets/aud/Mondo Drag - Fade Out.mp3",
"../assets/aud/Moon Walker - I’m Afraid I’ll Go To Heaven.mp3",
"../assets/aud/Morten Lauridsen, Chamber Choir Of Europe, Nicol Matt - O magnum mysterium.mp3",
"../assets/aud/Mother Mother - Arms Tonite.mp3",
"../assets/aud/Mother Mother - Bit By Bit.mp3",
"../assets/aud/Mother Mother - Burning Pile.mp3",
"../assets/aud/Mother Mother - Ghosting.mp3",
"../assets/aud/Mother Mother - Hayloft.mp3",
"../assets/aud/Mother Mother - Infinitesimal.mp3",
"../assets/aud/Mother Mother - Little Pistol.mp3",
"../assets/aud/Mother Mother - Miles.mp3",
"../assets/aud/Mother Mother - O My Heart.mp3",
"../assets/aud/Mother Mother - Sleep Awake.mp3",
"../assets/aud/Mother Mother - The Sticks.mp3",
"../assets/aud/Mother Mother - Wrecking Ball.mp3",
"../assets/aud/Moths.mp3",
"../assets/aud/Mötley Crüe - Dr. Feelgood.mp3",
"../assets/aud/Mr.Kitty - After Dark.mp3",
"../assets/aud/Ms. Lauryn Hill - Doo Wop (That Thing).mp3",
"../assets/aud/Mudvayne - Happy.mp3",
"../assets/aud/Mudvayne - Not Falling.mp3",
"../assets/aud/Mura Masa, Daniela Lalita - Drugs.mp3",
"../assets/aud/Muse - Feeling Good.mp3",
"../assets/aud/Mustard, Roddy Ricch - Ballin' (with Roddy Ricch).mp3",
"../assets/aud/My Chemical Romance - Cemetery Drive.mp3",
"../assets/aud/My Chemical Romance - Helena.mp3",
"../assets/aud/My Chemical Romance - Mama.mp3",
"../assets/aud/My Chemical Romance - Teenagers.mp3",
"../assets/aud/My Chemical Romance - Welcome to the Black Parade.mp3",
"../assets/aud/My Mind Is A Mountain.mp3",
"../assets/aud/Myrkur - Dronning Ellisiv.mp3",
"../assets/aud/Myrkur - Juniper.mp3",
"../assets/aud/Myrkur - Vinter.mp3",
"../assets/aud/Nancy Sinatra - These Boots Are Made For Walkin'.mp3",
"../assets/aud/Natasha Bedingfield - Unwritten.mp3",
"../assets/aud/Neil Young - Harvest Moon.mp3",
"../assets/aud/Nemahsis - what if i took it off for you.mp3",
"../assets/aud/Neon Trees - First Things First.mp3",
"../assets/aud/Nervous Breakdown.mp3",
"../assets/aud/New Order - Blue Monday.mp3",
"../assets/aud/New Order - Elegia - 2015 Remaster.mp3",
"../assets/aud/New Young Pony Club - Ice Cream.mp3",
"../assets/aud/Nia Archives - Luv Like.mp3",
"../assets/aud/Nicki Minaj - Super Bass.mp3",
"../assets/aud/Niko Ne Zna - Nebuchadnezzar's Nine Wives.mp3",
"../assets/aud/Nilüfer Yanya - midnight sun.mp3",
"../assets/aud/Nina Simone - Feeling Good.mp3",
"../assets/aud/Nina Simone - I Put A Spell On You.mp3",
"../assets/aud/Nine Inch Nails - Closer.mp3",
"../assets/aud/Nine Inch Nails - Hurt.mp3",
"../assets/aud/Nine Inch Nails - Into The Void.mp3",
"../assets/aud/Nirvana - Come As You Are (Lyrics).mp3",
"../assets/aud/Nirvana - Heart-Shaped Box (Lyrics).mp3",
"../assets/aud/Noa Lewis, ROMderful - Attention.mp3",
"../assets/aud/noonday underground - London.mp3",
"../assets/aud/Norma Tanega - A Street That Rhymes at 6am.mp3",
"../assets/aud/Norma Tanega - Bread.mp3",
"../assets/aud/Norma Tanega - Hey Girl.mp3",
"../assets/aud/Norma Tanega - You're Dead.mp3",
"../assets/aud/Nothing Breaks Like A Heart.mp3",
"../assets/aud/Nothing Matters.mp3",
"../assets/aud/NSG, Tion Wayne - Options.mp3",
"../assets/aud/Of Mice & Men - SECOND & SEBRING.mp3",
"../assets/aud/Of Monsters and Men - Human.mp3",
"../assets/aud/Of Monsters and Men - Wild Roses.mp3",
"../assets/aud/OG Luv Kush pt 2.mp3",
"../assets/aud/Oh, The Guilt - Ghost Box.mp3",
"../assets/aud/Oh, The Guilt - In Weird Sleep.mp3",
"../assets/aud/Oingo Boingo - No One Lives Forever.mp3",
"../assets/aud/Ol' Dirty Bastard, Kelis - Got Your Money (feat. Kelis).mp3",
"../assets/aud/One Way Road.mp3",
"../assets/aud/ONUKA - ZENIT.mp3",
"../assets/aud/Oracle Sisters - Asc. Scorpio.mp3",
"../assets/aud/Orville Peck - Big Sky.mp3",
"../assets/aud/Orville Peck - Buffalo Run.mp3",
"../assets/aud/Orville Peck - Dead of Night.mp3",
"../assets/aud/Orville Peck - Hope to Die.mp3",
"../assets/aud/Orville Peck - Kansas (Remembers Me Now).mp3",
"../assets/aud/Orville Peck - Nothing Fades Like the Light.mp3",
"../assets/aud/Orville Peck - Old River.mp3",
"../assets/aud/Orville Peck - Queen of the Rodeo.mp3",
"../assets/aud/Orville Peck - Roses Are Falling.mp3",
"../assets/aud/Orville Peck - Take You Back (The Iron Hoof Cattle Call).mp3",
"../assets/aud/Orville Peck - Turn to Hate.mp3",
"../assets/aud/Orville Peck - Winds Change.mp3",
"../assets/aud/Otis Redding - (Sittin' On) the Dock of the Bay.mp3",
"../assets/aud/Outkast - Hey Ya!.mp3",
"../assets/aud/Paige Kennedy - Lingerie Model.mp3",
"../assets/aud/Palm Springsteen - Hey There Cowgirl.mp3",
"../assets/aud/Panic! At The Disco - One of the Drunks.mp3",
"../assets/aud/Panic! At The Disco - This Is Gospel.mp3",
"../assets/aud/Paramore - Emergency.mp3",
"../assets/aud/Paramore - Rose-Colored Boy.mp3",
"../assets/aud/Paramore_ Pressure [OFFICIAL VIDEO].mp3",
"../assets/aud/Parquet Courts - Tenderness.mp3",
"../assets/aud/Passenger.mp3",
"../assets/aud/Patrick Watson - Je te laisserai des mots.mp3",
"../assets/aud/Pearl Jam - Just Breathe.mp3",
"../assets/aud/Perfect Stranger.mp3",
"../assets/aud/Petros Tabouris - Askaulos.mp3",
"../assets/aud/Phil Collins - In the Air Tonight.mp3",
"../assets/aud/PHILDEL - The Wolf.mp3",
"../assets/aud/Pierce The Veil - Bulls In The Bronx.mp3",
"../assets/aud/Pillow Queens - Rats (EP Version).mp3",
"../assets/aud/Pinc Louds - Soul in My Body.mp3",
"../assets/aud/Pink Maggit.mp3",
"../assets/aud/Pink Pony Club.mp3",
"../assets/aud/Pissed Jeans - The Bar Is Low.mp3",
"../assets/aud/Placebo - Daddy Cool.mp3",
"../assets/aud/Placebo - Every You Every Me.mp3",
"../assets/aud/Placebo - Pure Morning.mp3",
"../assets/aud/Poetry In Motion.mp3",
"../assets/aud/Pond - Paint Me Silver.mp3",
"../assets/aud/Pony.mp3",
"../assets/aud/Portishead - Glory Box.mp3",
"../assets/aud/Portishead - Roads.mp3",
"../assets/aud/Powerman 5000 - When Worlds Collide.mp3",
"../assets/aud/Primadonna Girl.mp3",
"../assets/aud/Prince - Kiss.mp3",
"../assets/aud/Psychedelic Porn Crumpets - Cornflake.mp3",
"../assets/aud/Pure Shores.mp3",
"../assets/aud/Queen - I Want To Break Free.mp3",
"../assets/aud/Queen - Killer Queen.mp3",
"../assets/aud/Queen - We Will Rock You - Remastered 2011.mp3",
"../assets/aud/R.E.M. - Losing My Religion.mp3",
"../assets/aud/R.E.M. - Man On The Moon.mp3",
"../assets/aud/R.E.M. - Shiny Happy People.mp3",
"../assets/aud/Radik Tyulush - Oskus Urug.mp3",
"../assets/aud/Rage Against The Machine - Bombtrack.mp3",
"../assets/aud/Rage Against The Machine - Bulls On Parade.mp3",
"../assets/aud/Rage Against The Machine - Fistful of Steel.mp3",
"../assets/aud/Rage Against The Machine - How I Could Just Kill a Man.mp3",
"../assets/aud/Rage Against The Machine - Killing In The Name.mp3",
"../assets/aud/Rage Against The Machine - Renegades Of Funk.mp3",
"../assets/aud/Rage Against The Machine - Take the Power Back.mp3",
"../assets/aud/Rage Against The Machine - Testify.mp3",
"../assets/aud/Rage Against The Machine - The Ghost of Tom Joad.mp3",
"../assets/aud/Ralph Hart And The Texas Musical Harts - Ain't No Grave Gonna Hold My Body Down.mp3",
"../assets/aud/Ralph Stanley - O Death.mp3",
"../assets/aud/Ramin Djawadi - Paint It, Black.mp3",
"../assets/aud/Rammstein - Deutschland.mp3",
"../assets/aud/Rammstein - Mein Land.mp3",
"../assets/aud/Ramones - Pet Sematary.mp3",
"../assets/aud/Ramones - Sheena Is a Punk Rocker - 2017 Remaster.mp3",
"../assets/aud/Raveena - Bloom.mp3",
"../assets/aud/Raveena - Headaches.mp3",
"../assets/aud/Raveena - Mama.mp3",
"../assets/aud/Raveena - Stone.mp3",
"../assets/aud/Raveena - Sweet Time.mp3",
"../assets/aud/Raveena, Hope Tala - Floating (feat. Hope Tala).mp3",
"../assets/aud/Real Love Baby.mp3",
"../assets/aud/Real Love.mp3",
"../assets/aud/Redbone - The Witch Queen of New Orleans.mp3",
"../assets/aud/Ren - Hi Ren.mp3",
"../assets/aud/Ren - Sick Boi.mp3",
"../assets/aud/Rick James - Super Freak.mp3",
"../assets/aud/Ricky Nelson - Lonesome Town.mp3",
"../assets/aud/Rihanna - Desperado.mp3",
"../assets/aud/Rina Sawayama - XS.mp3",
"../assets/aud/Rising Of The Moon.mp3",
"../assets/aud/Ritchie Sacramento.mp3",
"../assets/aud/Road Head.mp3",
"../assets/aud/Rob Zombie - Dragula.mp3",
"../assets/aud/Rob Zombie - Living Dead Girl.mp3",
"../assets/aud/Rob Zombie - Lords Of Salem.mp3",
"../assets/aud/Rob Zombie - Real Solution #9 - Live At Riot Fest  2016.mp3",
"../assets/aud/Robyn - Dancing On My Own.mp3",
"../assets/aud/Rock With You.mp3",
"../assets/aud/Rockwell - Somebody's Watching Me.mp3",
"../assets/aud/ROMderful - THE SUN SHINES SO BRIGHT WITH YOU.mp3",
"../assets/aud/Rough Trade - All Touch.mp3",
"../assets/aud/Roxette - How Do You Do!.mp3",
"../assets/aud/Roy Orbison - In Dreams.mp3",
"../assets/aud/Russian Circles - Vorel.mp3",
"../assets/aud/Rusted Root - Send Me on My Way.mp3",
"../assets/aud/Rx Queen.mp3",
"../assets/aud/Sad Girl Summer.mp3",
"../assets/aud/SAINt JHN - Roses.mp3",
"../assets/aud/SAINt JHN, Imanbek - Roses - Imanbek Remix.mp3",
"../assets/aud/Sampha - (No One Knows Me) Like the Piano.mp3",
"../assets/aud/Sampha - Plastic 100°C.mp3",
"../assets/aud/Sass.mp3",
"../assets/aud/Save Me.mp3",
"../assets/aud/Save Your Tears.mp3",
"../assets/aud/SBTRKT, Sampha - Hold On.mp3",
"../assets/aud/Scissor Sisters - FilthyGorgeous.mp3",
"../assets/aud/Seafret - Monsters.mp3",
"../assets/aud/Selah Sue, TOKiMONSTA - I Wish I Could (feat. Selah Sue).mp3",
"../assets/aud/Sergei Prokofiev, Orchestra of the Royal Opera House, Covent Garden, Mark Ermler - Romeo and Juliet, Op. 64 -  No. 13 Dance of the Knights.mp3",
"../assets/aud/Set It Off - Skeleton.mp3",
"../assets/aud/Sevdaliza - Darkest Hour.mp3",
"../assets/aud/Sevdaliza - Human.mp3",
"../assets/aud/Sevdaliza - Rhode.mp3",
"../assets/aud/Shannon & The Clams - The Boy.mp3",
"../assets/aud/Sharon Van Etten - Jupiter 4.mp3",
"../assets/aud/Shawn James - Chicago.mp3",
"../assets/aud/Shawn James - The Curse of the Fold.mp3",
"../assets/aud/Shawn James - The Thief and the Moon.mp3",
"../assets/aud/Shawn James - Through the Valley.mp3",
"../assets/aud/She Wants Revenge - Tear You Apart.mp3",
"../assets/aud/Shot You Down.mp3",
"../assets/aud/Sia - Ho Ho Ho.mp3",
"../assets/aud/Sigur Rós - Varúð.mp3",
"../assets/aud/Silve To Rust.mp3",
"../assets/aud/Siouxsie and the Banshees - Cities In Dust.mp3",
"../assets/aud/Siouxsie and the Banshees - Spellbound.mp3",
"../assets/aud/SiR - John Redcorn.mp3",
"../assets/aud/SiR - NO EVIL (Lyrics).mp3",
"../assets/aud/SiR, D.K. the Punisher, Fat Ron - In The Sky - DK The Punisher's 10th Anniv. Mix.mp3",
"../assets/aud/SiR, Kendrick Lamar - Hair Down (feat. Kendrick Lamar).mp3",
"../assets/aud/Sixpence None The Richer - Kiss Me.mp3",
"../assets/aud/SKEMER - Heartbreak.mp3",
"../assets/aud/Skunk Anansie - Weak.mp3",
"../assets/aud/Sleep Token - Granite.mp3",
"../assets/aud/Sleep Token - The Summoning.mp3",
"../assets/aud/Sleeping Bag.mp3",
"../assets/aud/Slint - Good Morning, Captain.mp3",
"../assets/aud/Slipknot - (sic).mp3",
"../assets/aud/Slipknot - Before I Forget.mp3",
"../assets/aud/Slipknot - Disasterpiece.mp3",
"../assets/aud/Slipknot - Psychosocial - 2012 Remaster.mp3",
"../assets/aud/Slipknot - Sulfur - 2012 Remaster.mp3",
"../assets/aud/Slipknot - Vermilion, Pt. 2.mp3",
"../assets/aud/Slipknot - Vermilion.mp3",
"../assets/aud/Slipknot - Wait and Bleed.mp3",
"../assets/aud/Snakehips, Kaleem Taylor - Forever (Pt. II) (feat. Kaleem Taylor).mp3",
"../assets/aud/Snakehips, Knox Brown, Chaz French - Déjà Vu (feat. Chaz French).mp3",
"../assets/aud/Soap&Skin - Me and the Devil.mp3",
"../assets/aud/Soap&Skin - Thanatos.mp3",
"../assets/aud/Something's Got A Hold Of Me.mp3",
"../assets/aud/Son Lux, Rafiq Bhatia - Easy.mp3",
"../assets/aud/Souvenir.mp3",
"../assets/aud/Sova.mp3",
"../assets/aud/Sowulo - Samhain.mp3",
"../assets/aud/SPELLES - Dead in the Water.mp3",
"../assets/aud/Spookie Coochie By. Iamdoechii (Audio).mp3",
"../assets/aud/Squirrel Nut Zippers - Ghost Of Stephen Foster.mp3",
"../assets/aud/Squirrel Nut Zippers - Hell - Remastered 2016.mp3",
"../assets/aud/Starbenders - Blood.mp3",
"../assets/aud/Starboy.mp3",
"../assets/aud/Stealers Wheel - Stuck In The Middle With You.mp3",
"../assets/aud/Stevie Nicks - 24 Karat Gold.mp3",
"../assets/aud/Stevie Nicks - Edge of Seventeen.mp3",
"../assets/aud/Still Woozy - Goodie Bag.mp3",
"../assets/aud/Stole.mp3",
"../assets/aud/Stolen Nova - Lauren Bacall.mp3",
"../assets/aud/Strawberry Letter 23.mp3",
"../assets/aud/Street Carp.mp3",
"../assets/aud/Stromae - L’enfer.mp3",
"../assets/aud/Stromae - La solassitude.mp3",
"../assets/aud/Stromae - Tous les mêmes.mp3",
"../assets/aud/Stupid Love.mp3",
"../assets/aud/Sturgill Simpson - The Dead Don't Die.mp3",
"../assets/aud/Sturm.mp3",
"../assets/aud/Substitute.mp3",
"../assets/aud/Surf Mesa, Emilee - ily (i love you baby) (feat. Emilee).mp3",
"../assets/aud/Surfbort - Big Star.mp3",
"../assets/aud/Sūrya - Black Snake Prophecy.mp3",
"../assets/aud/Sūrya - Fenland.mp3",
"../assets/aud/Susan Sarandon - Touch-A, Touch-A, Touch Me.mp3",
"../assets/aud/Swans - Love Will Save You.mp3",
"../assets/aud/Sweet - Ballroom Blitz.mp3",
"../assets/aud/System Of A Down - Attack.mp3",
"../assets/aud/System Of A Down - Deer Dance.mp3",
"../assets/aud/System Of A Down - Forest.mp3",
"../assets/aud/System Of A Down - Kill Rock 'n Roll.mp3",
"../assets/aud/System Of A Down - Sugar.mp3",
"../assets/aud/System Of A Down - Thetawaves.mp3",
"../assets/aud/t.A.T.u. - All The Things She Said.mp3",
"../assets/aud/Taco - Puttin' on the Ritz.mp3",
"../assets/aud/Talking Heads - Burning Down the House.mp3",
"../assets/aud/Talking Heads - Once in a Lifetime - 2005 Remaster.mp3",
"../assets/aud/Talking Heads - Psycho Killer.mp3",
"../assets/aud/Talking Heads - This Must Be the Place (Naive Melody) - 2005 Remaster.mp3",
"../assets/aud/Tame Impala - Borderline.mp3",
"../assets/aud/Taproot - Poem.mp3",
"../assets/aud/Teddy Hyde - Sex with a Ghost.mp3",
"../assets/aud/Teenager.mp3",
"../assets/aud/Tei Shi - Bassically - Acoustic.mp3",
"../assets/aud/Tei Shi - Bassically.mp3",
"../assets/aud/That's What You Get.mp3",
"../assets/aud/The Accidentals - Earthbound.mp3",
"../assets/aud/THE ANXIETY, WILLOW, Tyler Cole - Fight Club.mp3",
"../assets/aud/The B-52's - Love Shack.mp3",
"../assets/aud/the bird and the bee - Witch.mp3",
"../assets/aud/The Black Ghosts - Full Moon.mp3",
"../assets/aud/The Black Keys - Little Black Submarines.mp3",
"../assets/aud/The Blue Stones - Black Holes (Solid Ground).mp3",
"../assets/aud/The Brian Jonestown Massacre - Anemone.mp3",
"../assets/aud/The Byrds - You Ain't Goin' Nowhere.mp3",
"../assets/aud/The Cardigans - Carnival.mp3",
"../assets/aud/The Cardigans - My Favourite Game.mp3",
"../assets/aud/The Chemical Brothers - Block Rockin Beats.mp3",
"../assets/aud/The Clash - Should I Stay or Should I Go - Remastered.mp3",
"../assets/aud/The Coasters - Down in Mexico - Remastered.mp3",
"../assets/aud/The Cramps - Goo Goo Muck (Official Audio).mp3",
"../assets/aud/The Cramps - Human Fly.mp3",
"../assets/aud/The Cramps - Queen of Pain.mp3",
"../assets/aud/The Cranberries - Dreams.mp3",
"../assets/aud/The Cure - Boys Don't Cry.mp3",
"../assets/aud/The Cure - Close To Me.mp3",
"../assets/aud/The Dead South - In Hell I'll Be in Good Company.mp3",
"../assets/aud/The Decemberists - Rusalka, Rusalka  Wild Rushes.mp3",
"../assets/aud/The Decemberists - The Mariner's Revenge Song.mp3",
"../assets/aud/The Dhol Foundation - Thunder Drum.mp3",
"../assets/aud/The Diamonds - Batman, Wolfman, Frankenstein Or Dracula.mp3",
"../assets/aud/The Doors - Alabama Song (Whisky Bar).mp3",
"../assets/aud/The Five Blobs - The Blob.mp3",
"../assets/aud/The Flying Lizards - Money.mp3",
"../assets/aud/The Growlers - Vacant Lot.mp3",
"../assets/aud/The Irrepressibles - Two Men in Love.mp3",
"../assets/aud/The King.mp3",
"../assets/aud/The Mountain Goats - No Children.mp3",
"../assets/aud/The Mountain Goats - Werewolf Gimmick.mp3",
"../assets/aud/The Neighborhood Kids, Verde, Amon the MC, DJ JG - BIDDI BOMB.mp3",
"../assets/aud/The Notorious B.I.G. - Hypnotize - 2014 Remaster.mp3",
"../assets/aud/The Nude Party - Chevrolet Van.mp3",
"../assets/aud/The Offspring - Self Esteem.mp3",
"../assets/aud/The Pretty Reckless - Make Me Wanna Die.mp3",
"../assets/aud/The Prodigy - Breathe.mp3",
"../assets/aud/The Prodigy - Hotride.mp3",
"../assets/aud/The Prodigy - Spitfire.mp3",
"../assets/aud/The Raconteurs - Steady, As She Goes.mp3",
"../assets/aud/The Re-Stoned - Gift of the Lizard.mp3",
"../assets/aud/The Roots, Cody Chesnutt - The Seed (2.0).mp3",
"../assets/aud/The Smashing Pumpkins - Bullet With Butterfly Wings - Remastered 2012.mp3",
"../assets/aud/The Strokes - Reptilia.mp3",
"../assets/aud/The Troggs - Wild Thing.mp3",
"../assets/aud/The Undertones - Teenage Kicks.mp3",
"../assets/aud/The Viles, Madde - Come Off.mp3",
"../assets/aud/The Walking Tree - We Are Free.mp3",
"../assets/aud/The Weeknd - After Hours.mp3",
"../assets/aud/The Weeknd - Blinding Lights.mp3",
"../assets/aud/The Weeknd - Secrets.mp3",
"../assets/aud/The Weeknd, Chromatics, Johnny Jewel - Blinding Lights - Chromatics Remix.mp3",
"../assets/aud/The Weeknd, Daft Punk - I Feel It Coming.mp3",
"../assets/aud/The White Stripes - Blue Orchid.mp3",
"../assets/aud/The White Stripes - Hotel Yorba.mp3",
"../assets/aud/The Wombats - Greek Tragedy.mp3",
"../assets/aud/The Youngbloods - Darkness, Darkness.mp3",
"../assets/aud/The Zombie.mp3",
"../assets/aud/Thirty Seconds To Mars - Attack.mp3",
"../assets/aud/Thirty Seconds To Mars - The Kill (Bury Me).mp3",
"../assets/aud/Thom Yorke - Suspirium.mp3",
"../assets/aud/Three Days Grace - I Hate Everything About You.mp3",
"../assets/aud/Through Me (Through The Flood).mp3",
"../assets/aud/Tim Curry - Sweet Transvestite.mp3",
"../assets/aud/Timber Timbre - No Bold Villain.mp3",
"../assets/aud/TLC - No Scrubs.mp3",
"../assets/aud/Tobe Nwigwe - FRESH AIR.mp3",
"../assets/aud/Tobe Nwigwe, Fat Nwigwe - EAT.mp3",
"../assets/aud/Todrick Hall - Nails, Hair, Hips, Heels.mp3",
"../assets/aud/TOKiMONSTA - Bibimbap.mp3",
"../assets/aud/TOKiMONSTA - Corazón  Death by Disco Pt 2.mp3",
"../assets/aud/TOKiMONSTA - Gamble.mp3",
"../assets/aud/TOKiMONSTA - Lune.mp3",
"../assets/aud/TOKiMONSTA - Rose's Thorn.mp3",
"../assets/aud/TOKiMONSTA - Rouge.mp3",
"../assets/aud/TOKiMONSTA, Anderson .Paak - Realla.mp3",
"../assets/aud/TOKiMONSTA, Anderson .Paak, Rae Khalil - On Sum.mp3",
"../assets/aud/TOKiMONSTA, Bibi Bourelly, Jean Deaux - One Day - Instrumental.mp3",
"../assets/aud/TOKiMONSTA, Plastic Plates, Selah Sue - Early to Dawn (feat. Selah Sue) [Plastic Plates Remix].mp3",
"../assets/aud/TOKiMONSTA, Yuna - Don't Call Me (feat. Yuna).mp3",
"../assets/aud/Tom Rosenthal - Red Red Red.mp3",
"../assets/aud/Tom Waits - Goin' Out West.mp3",
"../assets/aud/Too Sweet.mp3",
"../assets/aud/Torn.mp3",
"../assets/aud/Tour Death Song.mp3",
"../assets/aud/Tove Lo - Habits (Stay High).mp3",
"../assets/aud/Townes Van Zandt - Don't Let The Sunshine Fool Ya'.mp3",
"../assets/aud/Townes Van Zandt - Heavenly Houseboat Blues.mp3",
"../assets/aud/Townes Van Zandt - If I Needed You.mp3",
"../assets/aud/Townes Van Zandt - Poncho & Lefty.mp3",
"../assets/aud/Townes Van Zandt - Silver Ships Of Andilar.mp3",
"../assets/aud/Trans-Siberian Orchestra - Christmas EveSarajevo 1224.mp3",
"../assets/aud/Tricky, Martina Topley-Bird - Hell Is Round The Corner.mp3",
"../assets/aud/Trixie Mattel - Video Games.mp3",
"../assets/aud/Two Feet - Devil.mp3",
"../assets/aud/Two Feet - I Feel Like I'm Drowning.mp3",
"../assets/aud/Ty Segall - Every 1's a Winner.mp3",
"../assets/aud/Type O Negative - I Don't Wanna Be Me.mp3",
"../assets/aud/Tzusing - Shame.mp3",
"../assets/aud/U-God - Knockin at Your Door.mp3",
"../assets/aud/Under The Table.mp3",
"../assets/aud/Unknown Mortal Orchestra - Dawn.mp3",
"../assets/aud/Unknown Mortal Orchestra - Faded in the Morning.mp3",
"../assets/aud/Unknown Mortal Orchestra - From the Sun.mp3",
"../assets/aud/Unknown Mortal Orchestra - Secret Xtians.mp3",
"../assets/aud/Unknown Mortal Orchestra - So Good At Being in Trouble.mp3",
"../assets/aud/Unknown Mortal Orchestra - Swim and Sleep (Like a Shark).mp3",
"../assets/aud/Unknown Mortal Orchestra - The Opposite of Afternoon.mp3",
"../assets/aud/Unloved - (Sigh).mp3",
"../assets/aud/Us3, Rahsaan, Gerard Presencer - Cantaloop (Flip Fantasia).mp3",
"../assets/aud/USHER - Caught Up.mp3",
"../assets/aud/UVWAYS - Beastie.mp3",
"../assets/aud/UVWAYS - Brothers of Light.mp3",
"../assets/aud/UVWAYS - Nineveh.mp3",
"../assets/aud/UVWAYS - Violence.mp3",
"../assets/aud/V V Brown - Shark In The Water.mp3",
"../assets/aud/Vargas & Lagola - Always.mp3",
"../assets/aud/Victor Hugo Fumagalli, Animor - VICTIMS of THE WOLF (original short film soundtrack).mp3",
"../assets/aud/Violent Femmes - Add It Up.mp3",
"../assets/aud/Violent Femmes - American Music.mp3",
"../assets/aud/Violent Femmes - Kiss Off.mp3",
"../assets/aud/Wardruna - Fehu.mp3",
"../assets/aud/Wardruna - Grá.mp3",
"../assets/aud/Wardruna - Helvegen - Skaldic Version.mp3",
"../assets/aud/Wardruna - Helvegen.mp3",
"../assets/aud/Wardruna - Kvitravn.mp3",
"../assets/aud/WARGASM (UK) - Post Modern Rhapsody.mp3",
"../assets/aud/WARGASM (UK) - Spit..mp3",
"../assets/aud/Warren Zevon - Werewolves of London.mp3",
"../assets/aud/We Are Broken.mp3",
"../assets/aud/Weird Awakenings.mp3",
"../assets/aud/Weyes Blood - Andromeda.mp3",
"../assets/aud/Weyes Blood - Movies.mp3",
"../assets/aud/WHALES•TALK - Ottawa Rockstar.mp3",
"../assets/aud/What It Is.mp3",
"../assets/aud/When It Rains.mp3",
"../assets/aud/White Reaper - Might Be Right.mp3",
"../assets/aud/Wildfires.mp3",
"../assets/aud/Wildflower And Barley.mp3",
"../assets/aud/Willie Bobo - Spanish Grease.mp3",
"../assets/aud/WILLOW - Wait a Minute!.mp3",
"../assets/aud/Witch - Seer.mp3",
"../assets/aud/Woodkid - Iron.mp3",
"../assets/aud/Y2K, bbno$ - Lalala.mp3",
"../assets/aud/Yann Tiersen - Comptine d'un autre été, l'après-midi.mp3",
"../assets/aud/Yeah Yeah Yeahs - Heads Will Roll.mp3",
"../assets/aud/Yemi Alade - Knack Am.mp3",
"../assets/aud/YONAKA - Seize the Power.mp3",
"../assets/aud/Young And In The Way - Solitude.mp3",
"../assets/aud/Yves Tumor - Gospel For A New Century.mp3",
"../assets/aud/Yves Tumor - Romanticist.mp3",
"../assets/aud/Zamilska - Rise.mp3",
"../assets/aud/Zeal & Ardor - Devil Is Fine.mp3",
"../assets/aud/Zeal & Ardor - Gravedigger's Chant.mp3",
"../assets/aud/ZZ Top - Gimme All Your Lovin'.mp3",
"../assets/aud/ZZ Top - Sharp Dressed Man (2008 Remaster).mp3",
"../assets/aud/Unreal Unearth",
"../assets/aud/_HOLI YAAD_  Gulabi Sapera & Titi Robin.mp3",
"../assets/aud/01 Careful.mp3",
"../assets/aud/01 STANKA POOH.mp3",
"../assets/aud/02 BULLFROG.mp3",
"../assets/aud/02 Ignorance.mp3", 
];